version: "3.8"
services:
  wordpress:
    image: wordpress:latest
    container_name: site1_wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WP_HOME: http://192.168.0.105:8001
      WP_SITEURL: http://192.168.0.105:8001
    volumes:
      - ./data/wp_content:/var/www/html
    ports:
      - "8001:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: site1_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./data/db:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: site1_nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend/my-react-app/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress